just_smtp.settings:
  type: config_object
  label: 'Just SMTP config.'
  mapping:
    just_smtp_on:
      type: boolean
      label: 'Turn this module on or off'
    just_smtp_host:
      type: string
      label: 'SMTP server'
    just_smtp_port:
      type: string
      label: 'SMTP port'
    just_smtp_protocol:
      type: string
      label: 'SMTP protocol'
    just_smtp_username:
      type: string
      label: 'Username'
    just_smtp_password:
      type: string
      label: 'Password'
    just_smtp_encrypt:
      type: boolean
      label: 'Encrypt password'
    just_smtp_encrypt_profile:
      type: string
      lable: 'Encryption profile'
    just_smtp_prior_mailsystem:
      type: string
      label: 'Prior Mailsystem'
